type User @node {
  id: ID! @id            
  username: String! @unique
  hashedPassword: String! @private        
  email: String!  @unique
  events: [Event!]! @relationship(type: "CREATED", direction: OUT)           
}

input SignUpInput {
    email: String!
    password: String!
}

input LoginInput {
    email: String!
    password: String!
}

type LoginResponse {
    success: Boolean!
    message: String!
    accessToken: String!
    refreshToken: String!
}

type SignUpResponse {
    success: Boolean!
    message: String!
    user: User
}

type Mutation {
    signUp(input: SignUpInput!): SignUpResponse!,
    login(input: LoginInput!): LoginResponse!
}